[Appearance]
color_scheme_path=/home/netus/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
icon_theme=Adwaita

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\xb9\0\0\x4\b\0\0\0\0\0\0\0\0\0\0\x3\xb9\0\0\x4\b\0\0\0\x1\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xb9\0\0\x4\b)
